# Generated by Django 6.0.8 on 2026-09-06 07:31

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='رقم المشروع')),
                ('public_name', models.CharField(max_length=200, verbose_name='اسم العرض')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='اسم العميل الداخلي')),
                ('work_type', models.CharField(choices=[('structure', 'عظم'), ('finishing', 'تشطيب'), ('both', 'عظم وتشطيب')], max_length=20, verbose_name='نوع الأعمال')),
                ('area', models.CharField(max_length=100, verbose_name='المنطقة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف العام')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='خط العرض')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='خط الطول')),
                ('is_public', models.BooleanField(default=False, verbose_name='إظهار على الخريطة العامة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['reference'],
            },
        ),
    ]
